"""initial schema — Step 6's six tables (tenants, api_keys, borrowers,
applications, audit_events, idempotency_keys), no RLS yet (see 0002).

Revision ID: 0001
Revises:
Create Date: 2026-08-13 16:18:14.545728

"""

from __future__ import annotations

from collections.abc import Sequence

import sqlalchemy as sa
from alembic import op
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = "0001"
down_revision: str | None = None
branch_labels: str | Sequence[str] | None = None
depends_on: str | Sequence[str] | None = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table(
        "tenants",
        sa.Column("id", sa.Uuid(), nullable=False),
        sa.Column("slug", sa.String(length=64), nullable=False),
        sa.Column("legal_name", sa.String(length=256), nullable=False),
        sa.Column("status", sa.String(length=16), nullable=False),
        sa.Column("residency_region", sa.String(length=32), nullable=False),
        sa.Column("retention_days_raw", sa.Integer(), nullable=False),
        sa.Column(
            "created_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.Column(
            "updated_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.CheckConstraint(
            "status IN ('ACTIVE', 'SUSPENDED', 'OFFBOARDED')", name="ck_tenants_status"
        ),
        sa.CheckConstraint("retention_days_raw > 0", name="ck_tenants_retention_positive"),
        sa.PrimaryKeyConstraint("id", name=op.f("pk_tenants")),
        sa.UniqueConstraint("slug", name=op.f("uq_tenants_slug")),
    )
    op.create_table(
        "api_keys",
        sa.Column("id", sa.Uuid(), nullable=False),
        sa.Column("tenant_id", sa.Uuid(), nullable=False),
        sa.Column("key_hash", sa.String(length=128), nullable=False),
        sa.Column("label", sa.String(length=128), nullable=False),
        sa.Column("last_used_at", sa.DateTime(timezone=True), nullable=True),
        sa.Column("revoked_at", sa.DateTime(timezone=True), nullable=True),
        sa.Column(
            "created_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.ForeignKeyConstraint(
            ["tenant_id"], ["tenants.id"], name=op.f("fk_api_keys_tenant_id_tenants")
        ),
        sa.PrimaryKeyConstraint("id", name=op.f("pk_api_keys")),
        sa.UniqueConstraint("key_hash", name=op.f("uq_api_keys_key_hash")),
    )
    op.create_index("ix_api_keys_tenant_id", "api_keys", ["tenant_id"], unique=False)
    op.create_table(
        "audit_events",
        sa.Column("id", sa.Uuid(), nullable=False),
        sa.Column("tenant_id", sa.Uuid(), nullable=False),
        sa.Column("entity_type", sa.String(length=64), nullable=False),
        sa.Column("entity_id", sa.Uuid(), nullable=False),
        sa.Column("event_type", sa.String(length=64), nullable=False),
        sa.Column("actor_type", sa.String(length=16), nullable=False),
        sa.Column("actor_id", sa.String(length=128), nullable=True),
        sa.Column(
            "payload_json",
            postgresql.JSONB(astext_type=sa.Text()),
            server_default="{}",
            nullable=False,
        ),
        sa.Column("occurred_at", sa.DateTime(timezone=True), nullable=False),
        sa.Column(
            "recorded_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.Column("prev_hash", sa.String(length=64), nullable=True),
        sa.Column("event_hash", sa.String(length=64), nullable=False),
        sa.CheckConstraint(
            "actor_type IN ('api_key', 'system')", name="ck_audit_events_actor_type"
        ),
        sa.ForeignKeyConstraint(
            ["tenant_id"], ["tenants.id"], name=op.f("fk_audit_events_tenant_id_tenants")
        ),
        sa.PrimaryKeyConstraint("id", name=op.f("pk_audit_events")),
    )
    op.create_index("ix_audit_events_tenant_id", "audit_events", ["tenant_id"], unique=False)
    op.create_index(
        "ix_audit_events_tenant_id_entity",
        "audit_events",
        ["tenant_id", "entity_type", "entity_id"],
        unique=False,
    )
    op.create_table(
        "borrowers",
        sa.Column("id", sa.Uuid(), nullable=False),
        sa.Column("tenant_id", sa.Uuid(), nullable=False),
        sa.Column("entity_type", sa.String(length=16), nullable=False),
        sa.Column("legal_name", sa.String(length=256), nullable=False),
        sa.Column("pan", sa.String(length=10), nullable=False),
        sa.Column("gstin", sa.String(length=15), nullable=False),
        sa.Column("udyam", sa.String(length=19), nullable=True),
        sa.Column("primary_mobile_hash", sa.String(length=128), nullable=True),
        sa.Column(
            "created_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.Column(
            "updated_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.CheckConstraint(
            "entity_type IN ('PROPRIETORSHIP', 'PARTNERSHIP', 'LLP', 'PVT_LTD')",
            name="ck_borrowers_entity_type",
        ),
        sa.CheckConstraint("length(gstin) = 15", name="ck_borrowers_gstin_length"),
        sa.CheckConstraint("length(pan) = 10", name="ck_borrowers_pan_length"),
        sa.ForeignKeyConstraint(
            ["tenant_id"], ["tenants.id"], name=op.f("fk_borrowers_tenant_id_tenants")
        ),
        sa.PrimaryKeyConstraint("id", name=op.f("pk_borrowers")),
        sa.UniqueConstraint("tenant_id", "gstin", name="uq_borrowers_tenant_gstin"),
        sa.UniqueConstraint("tenant_id", "pan", name="uq_borrowers_tenant_pan"),
    )
    op.create_index("ix_borrowers_tenant_id", "borrowers", ["tenant_id"], unique=False)
    op.create_table(
        "idempotency_keys",
        sa.Column("id", sa.Uuid(), nullable=False),
        sa.Column("tenant_id", sa.Uuid(), nullable=False),
        sa.Column("key", sa.String(length=256), nullable=False),
        sa.Column("request_fingerprint", sa.String(length=64), nullable=False),
        sa.Column("response_status", sa.Integer(), nullable=False),
        sa.Column("response_body", postgresql.JSONB(astext_type=sa.Text()), nullable=False),
        sa.Column(
            "created_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.Column("expires_at", sa.DateTime(timezone=True), nullable=False),
        sa.ForeignKeyConstraint(
            ["tenant_id"], ["tenants.id"], name=op.f("fk_idempotency_keys_tenant_id_tenants")
        ),
        sa.PrimaryKeyConstraint("id", name=op.f("pk_idempotency_keys")),
        sa.UniqueConstraint("tenant_id", "key", name="uq_idempotency_keys_tenant_key"),
    )
    op.create_index(
        "ix_idempotency_keys_tenant_id", "idempotency_keys", ["tenant_id"], unique=False
    )
    op.create_table(
        "applications",
        sa.Column("id", sa.Uuid(), nullable=False),
        sa.Column("tenant_id", sa.Uuid(), nullable=False),
        sa.Column("borrower_id", sa.Uuid(), nullable=False),
        sa.Column("external_ref", sa.String(length=128), nullable=False),
        sa.Column("requested_amount_paise", sa.BigInteger(), nullable=False),
        sa.Column("tenure_months", sa.Integer(), nullable=False),
        sa.Column("purpose", sa.String(length=32), nullable=False),
        sa.Column("status", sa.String(length=32), nullable=False),
        sa.Column("as_of", sa.DateTime(timezone=True), nullable=False),
        sa.Column(
            "received_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.Column(
            "created_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.Column(
            "updated_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.CheckConstraint(
            "purpose IN ('INVENTORY_PURCHASE', 'RAW_MATERIAL_PURCHASE', "
            "'RECEIVABLES_FINANCING', 'OPERATING_EXPENSES', 'SEASONAL_WORKING_CAPITAL', "
            "'BUSINESS_EXPANSION', 'OTHER_WORKING_CAPITAL')",
            name="ck_applications_purpose",
        ),
        sa.CheckConstraint(
            "status IN ('RECEIVED', 'VALIDATED', 'REJECTED_INTAKE', 'CONSENT_PENDING', "
            "'CONSENT_GRANTED', 'CONSENT_REJECTED', 'DATA_FETCHING', 'DATA_READY', "
            "'UNDERWRITING_IN_PROGRESS', 'PENDING_HUMAN_REVIEW', 'DECIDED', 'WITHDRAWN', "
            "'EXPIRED')",
            name="ck_applications_status",
        ),
        sa.CheckConstraint(
            "requested_amount_paise >= 0", name="ck_applications_amount_non_negative"
        ),
        sa.CheckConstraint("tenure_months > 0", name="ck_applications_tenure_positive"),
        sa.ForeignKeyConstraint(
            ["borrower_id"], ["borrowers.id"], name=op.f("fk_applications_borrower_id_borrowers")
        ),
        sa.ForeignKeyConstraint(
            ["tenant_id"], ["tenants.id"], name=op.f("fk_applications_tenant_id_tenants")
        ),
        sa.PrimaryKeyConstraint("id", name=op.f("pk_applications")),
        sa.UniqueConstraint(
            "tenant_id", "external_ref", name="uq_applications_tenant_external_ref"
        ),
    )
    op.create_index("ix_applications_tenant_id", "applications", ["tenant_id"], unique=False)
    op.create_index(
        "ix_applications_tenant_id_status", "applications", ["tenant_id", "status"], unique=False
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index("ix_applications_tenant_id_status", table_name="applications")
    op.drop_index("ix_applications_tenant_id", table_name="applications")
    op.drop_table("applications")
    op.drop_index("ix_idempotency_keys_tenant_id", table_name="idempotency_keys")
    op.drop_table("idempotency_keys")
    op.drop_index("ix_borrowers_tenant_id", table_name="borrowers")
    op.drop_table("borrowers")
    op.drop_index("ix_audit_events_tenant_id_entity", table_name="audit_events")
    op.drop_index("ix_audit_events_tenant_id", table_name="audit_events")
    op.drop_table("audit_events")
    op.drop_index("ix_api_keys_tenant_id", table_name="api_keys")
    op.drop_table("api_keys")
    op.drop_table("tenants")
    # ### end Alembic commands ###
