"""Tenant API key hashing.

HMAC-SHA256 keyed by the server-side pepper (`API_KEY_PEPPER`) —
deliberately NOT a slow password KDF (argon2/bcrypt/scrypt). API keys are
high-entropy random secrets generated by us, not human-chosen passwords:
a slow KDF adds real latency on every authenticated request with no
security benefit against an attacker who doesn't already have the pepper,
and the pepper is exactly what protects a leaked `key_hash` column from
offline brute force. See phase1.txt Step 8.

The resulting hash is looked up by equality against the unique-indexed
`api_keys.key_hash` column (see db/models/api_key.py) — this is the
standard, secure pattern for API key storage (the security boundary is the
keyed HMAC, not a linear/timing-safe scan of every row).
"""

from __future__ import annotations

import hashlib
import hmac


def hash_api_key(raw_key: str, pepper: str) -> str:
    return hmac.new(pepper.encode("utf-8"), raw_key.encode("utf-8"), hashlib.sha256).hexdigest()


def verify_api_key(raw_key: str, stored_hash: str, pepper: str) -> bool:
    """Constant-time comparison against an already-retrieved stored hash —
    defense in depth on top of the equality-indexed DB lookup."""
    return hmac.compare_digest(hash_api_key(raw_key, pepper), stored_hash)
